version: '3.8'

services:


  fmd-db:
    image: postgres:14-alpine
    container_name: local-fmd-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=fmdDB
      - POSTGRES_USER=aidoc_user
      - POSTGRES_PASSWORD=aidoc_password
    volumes:
      - fmd-db-data:/var/lib/postgresql/data
      - ./config/postgres/init:/docker-entrypoint-initdb.d
    networks:
      - ewm-network

volumes:
  fmd-db-data:

networks:
  ewm-network:
    driver: bridge