services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: aidoc_user
      POSTGRES_PASSWORD: aidoc_password
      POSTGRES_DB: aidoc_postgres_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api-gateway:
    build:
      context: .
      dockerfile: docker/api-gateway/Dockerfile
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/aidoc_postgres_db
      SPRING_DATASOURCE_USERNAME: aidoc_user
      SPRING_DATASOURCE_PASSWORD: aidoc_password
    ports:
      - "8080:8080"

  auth-server:
    build:
      context: .
      dockerfile: docker/auth-server/Dockerfile
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/aidoc_postgres_db
      SPRING_DATASOURCE_USERNAME: aidoc_user
      SPRING_DATASOURCE_PASSWORD: aidoc_password
    ports:
      - "8081:8081"

volumes:
  postgres_data: