spring:
  main:
    web-application-type: reactive
  datasource:
    url: jdbc:postgresql://localhost:5432/aidoc_db
    username: aidoc_user  # замените на ваш PostgreSQL логин
    password: aidoc_password  # замените на ваш PostgreSQL пароль
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  cloud:
    gateway:
      routes:
        - id: auth-server
          uri: http://localhost:8081
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
        - id: report-generation-service
          uri: http://localhost:8082
          predicates:
            - Path=/reports/**
        - id: document-service
          uri: http://localhost:8083
          predicates:
            - Path=/documents/**
jwt:
  secret: YourJWTSecretKey  # замените на ваш секретный ключ JWT
logging:
  level:
    org:
      springframework:
        security: DEBUG
